### ISSUE TITLE
can't do pull request

### ISSUE THREAD

**Issue by nahidalam** [isaacmg/healthcare_ml#4]
I wanted to add some NLP tools. I already updated the readme on my local branch but the upstream pull request failed.

`git pull upstream master && git push origin master`

**Comment by isaacmg** [comment]
So is the problem that you cannot push to your fork? Or are you having trouble with making the PR itself?

**Comment by nahidalam** [comment]
Can't push my fork, getting error
`fatal: unable to access 'https://github.com/isaacmg/healthcare_ml/': The requested URL returned error: 403`

**Comment by isaacmg** [comment]
At first glance it looks like you are trying to push directly to my master branch at  https://github.com/isaacmg/healthcare_ml/ rather than your own fork. I'd recommend trying something like `git set-url origin https://github.com/nahidalam/healthcare_ml.git` alternatively you could add another remote  and push to that. For more see this SO answer [https://stackoverflow.com/questions/25545613/how-can-i-push-to-my-fork-from-a-clone-of-the-original-repo](https://stackoverflow.com/questions/25545613/how-can-i-push-to-my-fork-from-a-clone-of-the-original-repo) . After that create the PR as normal.

**Comment by nahidalam** [comment]
Thanks. Got it. You should see the new pull request now.
